import type { User, ToolSchema, AuditLog } from '@toolforge/shared';

// Demo Users
export const demoUsers: (User & { password: string })[] = [
  {
    _id: 'user-1',
    email: 'soumayadmin@gmail.com',
    password: 'password',
    name: 'Soumay Admin',
    role: 'admin',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'user-2',
    email: 'soumaymanager@gmail.com',
    password: 'password',
    name: 'Soumay Manager',
    role: 'manager',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'user-3',
    email: 'soumayagent@gmail.com',
    password: 'password',
    name: 'Soumay Agent',
    role: 'agent',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'user-4',
    email: 'soumayviewer@gmail.com',
    password: 'password',
    name: 'Soumay Viewer',
    role: 'viewer',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Support Tickets Schema
export const supportTicketsSchema: ToolSchema = {
  _id: 'schema-1',
  toolId: 'support-tickets',
  name: 'Support Tickets',
  description: 'Manage customer support tickets',
  icon: 'ticket',
  resource: 'tickets',
  fields: [
    {
      key: 'title',
      label: 'Title',
      type: 'text',
      required: true,
      validation: { minLength: 3, maxLength: 200 },
      placeholder: 'Enter ticket title',
    },
    {
      key: 'description',
      label: 'Description',
      type: 'textarea',
      required: true,
      validation: { minLength: 10 },
      placeholder: 'Describe the issue in detail',
    },
    {
      key: 'priority',
      label: 'Priority',
      type: 'select',
      required: true,
      default: 'medium',
      options: [
        { value: 'low', label: 'Low' },
        { value: 'medium', label: 'Medium' },
        { value: 'high', label: 'High' },
      ],
    },
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      required: true,
      default: 'new',
      options: [
        { value: 'new', label: 'New' },
        { value: 'open', label: 'Open' },
        { value: 'pending', label: 'Pending' },
        { value: 'resolved', label: 'Resolved' },
        { value: 'closed', label: 'Closed' },
      ],
    },
    {
      key: 'assignee',
      label: 'Assignee',
      type: 'text',
      required: false,
    },
    {
      key: 'tags',
      label: 'Tags',
      type: 'multiselect',
      required: false,
      options: [
        { value: 'bug', label: 'Bug' },
        { value: 'feature', label: 'Feature Request' },
        { value: 'question', label: 'Question' },
        { value: 'urgent', label: 'Urgent' },
        { value: 'billing', label: 'Billing' },
      ],
    },
    {
      key: 'customerEmail',
      label: 'Customer Email',
      type: 'text',
      required: true,
      validation: { pattern: '^[^@]+@[^@]+\\.[^@]+$', patternMessage: 'Invalid email format' },
    },
  ],
  listView: {
    columns: [
      { key: 'title', label: 'Title', sortable: true },
      { key: 'status', label: 'Status', sortable: true },
      { key: 'priority', label: 'Priority', sortable: true },
      { key: 'customerEmail', label: 'Customer', sortable: true },
      { key: 'createdAt', label: 'Created', sortable: true },
    ],
    defaultSort: { field: 'createdAt', direction: 'desc' },
    filters: [
      {
        key: 'status',
        label: 'Status',
        type: 'multiselect',
        options: [
          { value: 'new', label: 'New' },
          { value: 'open', label: 'Open' },
          { value: 'pending', label: 'Pending' },
          { value: 'resolved', label: 'Resolved' },
          { value: 'closed', label: 'Closed' },
        ],
      },
      {
        key: 'priority',
        label: 'Priority',
        type: 'select',
        options: [
          { value: 'low', label: 'Low' },
          { value: 'medium', label: 'Medium' },
          { value: 'high', label: 'High' },
        ],
      },
    ],
    pageSize: 20,
    searchableFields: ['title', 'description', 'customerEmail'],
  },
  formView: {
    sections: [
      {
        title: 'Ticket Information',
        description: 'Basic ticket details',
        fields: ['title', 'description', 'customerEmail'],
      },
      {
        title: 'Classification',
        description: 'Categorize the ticket',
        fields: ['priority', 'status', 'tags'],
      },
      {
        title: 'Assignment',
        description: 'Assign the ticket',
        fields: ['assignee'],
      },
    ],
  },
  actions: [
    {
      id: 'assign-to-me',
      label: 'Assign to Me',
      type: 'row',
      icon: 'user',
      handler: 'assignToMe',
      permissions: ['admin', 'manager', 'agent'],
    },
    {
      id: 'bulk-change-status',
      label: 'Change Status',
      type: 'bulk',
      icon: 'edit',
      handler: 'bulkChangeStatus',
      permissions: ['admin', 'manager', 'agent'],
      confirmMessage: 'Are you sure you want to change the status of selected tickets?',
    },
  ],
  permissions: {
    canAccessTool: ['admin', 'manager', 'agent', 'viewer'],
    canCreate: ['admin', 'manager', 'agent'],
    canRead: ['admin', 'manager', 'agent', 'viewer'],
    canUpdate: ['admin', 'manager', 'agent'],
    canDelete: ['admin', 'manager'],
    canViewAuditLog: ['admin', 'manager'],
  },
  audit: {
    enabled: true,
    fields: ['title', 'description', 'status', 'priority', 'assignee', 'tags'],
  },
  version: 1,
  isPublished: true,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  publishedAt: new Date().toISOString(),
};

// Sample Tickets
export const sampleTickets = [
  {
    _id: 'ticket-1',
    title: 'Cannot login to my account',
    description: 'I have been trying to login for the past hour but keep getting an error message saying "Invalid credentials". I have reset my password twice but still cannot access my account.',
    priority: 'high',
    status: 'open',
    tags: ['bug', 'urgent'],
    customerEmail: 'john.doe@example.com',
    assignee: 'Soumay Agent',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'ticket-2',
    title: 'Request for new feature: Dark mode',
    description: 'It would be great if the application had a dark mode option for better viewing at night. Many users have been asking for this feature.',
    priority: 'low',
    status: 'new',
    tags: ['feature'],
    customerEmail: 'jane.smith@example.com',
    assignee: '',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'ticket-3',
    title: 'Billing discrepancy on invoice #12345',
    description: 'I was charged twice for my subscription this month. Please review and refund the duplicate charge. The transaction IDs are TXN-001 and TXN-002.',
    priority: 'high',
    status: 'pending',
    tags: ['billing', 'urgent'],
    customerEmail: 'bob.wilson@example.com',
    assignee: 'Soumay Manager',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'ticket-4',
    title: 'How to export data?',
    description: 'I need to export all my data from the platform. What format options are available? Can I get it in CSV or JSON format?',
    priority: 'medium',
    status: 'resolved',
    tags: ['question'],
    customerEmail: 'alice.johnson@example.com',
    assignee: 'Soumay Agent',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'ticket-5',
    title: 'Page loading very slowly',
    description: 'The dashboard page takes over 30 seconds to load. This started happening yesterday after the update. Other pages seem fine.',
    priority: 'medium',
    status: 'open',
    tags: ['bug'],
    customerEmail: 'charlie.brown@example.com',
    assignee: 'Soumay Agent',
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'ticket-6',
    title: 'Need help with API integration',
    description: 'We are trying to integrate your API with our system but getting 403 errors. We have checked our API keys and they seem correct.',
    priority: 'medium',
    status: 'new',
    tags: ['question'],
    customerEmail: 'dev@techcorp.com',
    assignee: '',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'ticket-7',
    title: 'Account upgrade not reflected',
    description: 'I upgraded my account to premium yesterday but still seeing the free tier limitations. Payment was successful.',
    priority: 'high',
    status: 'open',
    tags: ['billing'],
    customerEmail: 'premium.user@email.com',
    assignee: 'Soumay Manager',
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'ticket-8',
    title: 'Mobile app crashes on startup',
    description: 'After the latest update, the mobile app crashes immediately when I try to open it. I am using iOS 17.2 on iPhone 15.',
    priority: 'high',
    status: 'pending',
    tags: ['bug', 'urgent'],
    customerEmail: 'mobile.user@gmail.com',
    assignee: 'Soumay Agent',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
];

// Sample Audit Logs
export const sampleAuditLogs: AuditLog[] = [
  {
    _id: 'audit-1',
    actorUserId: 'user-3',
    actorEmail: 'soumayagent@gmail.com',
    role: 'agent',
    toolId: 'support-tickets',
    resource: 'tickets',
    recordId: 'ticket-1',
    actionType: 'UPDATE',
    diff: [
      { field: 'status', before: 'new', after: 'open' },
      { field: 'assignee', before: '', after: 'Soumay Agent' },
    ],
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'audit-2',
    actorUserId: 'user-2',
    actorEmail: 'soumaymanager@gmail.com',
    role: 'manager',
    toolId: 'support-tickets',
    resource: 'tickets',
    recordId: 'ticket-3',
    actionType: 'UPDATE',
    diff: [
      { field: 'status', before: 'open', after: 'pending' },
    ],
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
];

export const demoSchemas: ToolSchema[] = [supportTicketsSchema];
