// Question bank for the PillCare assistant. Keep answers concise and actionable.
export interface FAQItem {
  question: string;
  answer: string;
  tags?: string[];
}

export const assistantFAQs: FAQItem[] = [
  { question: "When should I refill compartment A?", answer: "Check pills remaining. If fewer than 3 days of doses remain, schedule a refill and enable a reminder." },
  { question: "How do I set a refill reminder?", answer: "Open Refill Reminders, pick the compartment, tap Set Reminder, and choose a date before pills run out." },
  { question: "What if I miss a dose?", answer: "Take it as soon as you remember unless it’s close to the next dose—then skip and resume. Do not double up." },
  { question: "Can I take aspirin with food?", answer: "Yes, take aspirin with food and water to reduce stomach irritation." },
  { question: "How do I enable biometric login?", answer: "Go to Profile → Preferences → Biometric Login and turn it on. A device fingerprint/Face ID must be enrolled." },
  { question: "How do I change my email?", answer: "Profile → Account → Email. Update and save; next login will require the new email." },
  { question: "How do I change my password?", answer: "Profile → Account → Password. Save changes, then use the new password next login." },
  { question: "How do I change my name?", answer: "Profile → Account → Name. Save changes and the profile header will update." },
  { question: "How to switch dark and light mode?", answer: "Profile → Preferences → Dark Mode toggle. The app remembers your choice." },
  { question: "How do I view refill days left?", answer: "On the dashboard under Refill Reminders; each compartment shows pills remaining and days left." },
  { question: "How to add a new medication?", answer: "Use the Add Medication flow (if enabled) or replace an existing slot’s details in the schedule screen." },
  { question: "What is adherence?", answer: "Adherence tracks how often you take meds on time. Higher adherence improves safety and outcomes." },
  { question: "How do I see my adherence?", answer: "Check the dashboard stats and streak cards. They summarize recent adherence performance." },
  { question: "How do I contact my caregiver?", answer: "Use the Messages tab to chat. Send a message and wait for a reply." },
  { question: "How do I silence notifications?", answer: "Use your device’s system Do Not Disturb. The app follows system notification settings." },
  { question: "How do I re-enable notifications?", answer: "Turn off Do Not Disturb or enable app notifications in system settings." },
  { question: "What happens if I take a double dose?", answer: "Do not take extra to compensate. Contact your clinician or poison control if you overdosed." },
  { question: "Can I delay a dose?", answer: "Short delays (≤1 hour) are usually fine; large delays may require skipping. Ask your clinician for rules per medication." },
  { question: "Can I take aspirin with caffeine?", answer: "Moderate caffeine is usually fine. Avoid adding more NSAIDs unless directed by a clinician." },
  { question: "How do I log a missed dose?", answer: "Use the missed-dose action if available, or note it in chat so the assistant can adjust reminders." },
  { question: "How do I reset my schedule?", answer: "Go to the schedule screen, edit times for each compartment, and save. The new times drive notifications." },
  { question: "How do I pause reminders?", answer: "Use a pause/snooze control if available, otherwise disable notifications in system settings temporarily." },
  { question: "Can I share my data with a caregiver?", answer: "If caregiver linking is enabled, invite them via the caregiver tab or provide access through your clinician." },
  { question: "How do I update my profile picture?", answer: "Use the profile avatar control if available. Otherwise it stays the default icon." },
  { question: "How many pills fit per compartment?", answer: "Follow your device’s capacity. Ensure pills do not exceed the compartment’s safe limit." },
  { question: "Can I mix different pills in one compartment?", answer: "Avoid mixing unless instructed by a clinician. It’s safer to separate by medication and time." },
  { question: "How do I know my next dose time?", answer: "Check the countdown on the dashboard; it shows the next scheduled dose." },
  { question: "What if a pill is missing?", answer: "Treat it as a missed dose and follow the missed-dose guidance. Refill the compartment." },
  { question: "Can I use the app offline?", answer: "Core tracking works offline. Sync and messaging may require connectivity." },
  { question: "How do I sync data?", answer: "The app syncs automatically when online. Keep the app open briefly to allow sync." },
  { question: "How do I export my data?", answer: "Use the Backup/Export option in Profile if available. Otherwise contact support for export." },
  { question: "How do I update the app?", answer: "Install updates from the Play Store. Staying current ensures notifications and security." },
  { question: "What if notifications are late?", answer: "Check battery optimization settings; allow the app to run in background and send notifications." },
  { question: "Can I use multiple devices?", answer: "Yes, but ensure you sign in with the same account so schedule and adherence stay synced." },
  { question: "How do I remove a medication?", answer: "Edit the compartment’s schedule and clear or replace the medication details." },
  { question: "How do I set morning and evening doses?", answer: "Set multiple dose times per day for a medication; the app will alert at each time." },
  { question: "Can I schedule PRN meds?", answer: "If PRN support exists, log them as needed and avoid exceeding maximum daily limits." },
  { question: "Can I add notes to a dose?", answer: "Use the note/comment field if available. Otherwise message your caregiver with the note." },
  { question: "How do I check drug interactions?", answer: "Ask the assistant with drug names; for medical decisions, confirm with a clinician or pharmacist." },
  { question: "How do I handle side effects?", answer: "If mild, note them and monitor. If severe (trouble breathing, swelling, chest pain), seek emergency care." },
  { question: "Can I adjust dose size?", answer: "Only adjust per clinician direction. Update the schedule to reflect the prescribed dose." },
  { question: "How do I add a caregiver?", answer: "Use the caregiver invite feature if enabled, or share your data through your clinician." },
  { question: "How do I remove a caregiver?", answer: "Use caregiver management to revoke access, or contact support to remove linked caregivers." },
  { question: "How do I verify time zone?", answer: "Ensure your device time zone is correct; the app follows device time for schedules." },
  { question: "Will traveling change my schedule?", answer: "Travel adjusts with device time. Review schedule after changing time zones to avoid missed doses." },
  { question: "Can I snooze a reminder?", answer: "Tap snooze on the reminder if available; otherwise set a new alarm within the app." },
  { question: "What if I take meds early?", answer: "Log as taken early if possible. Avoid taking the next dose too soon; ask if you need to adjust the schedule." },
  { question: "How do I see streaks?", answer: "Check the dashboard streak cards (e.g., 7-day, 30-day) for adherence streaks." },
  { question: "How do I view messages?", answer: "Open the Messages tab to read and send messages with caregivers or the assistant." },
  { question: "Is my data private?", answer: "Data is stored securely per platform standards. Avoid sharing your credentials." },
  { question: "How do I change language?", answer: "Use the language setting if available; otherwise system language is used." },
  { question: "Can I back up to cloud?", answer: "Yes, if cloud backup is enabled. Ensure you’re signed in and online." },
  { question: "How do I restore after reinstall?", answer: "Sign in with the same account. Your schedule and data will sync from the cloud." },
  { question: "Can I turn off biometric login?", answer: "Yes. Profile → Preferences → Biometric Login toggle off." },
  { question: "How do I report a missed reminder?", answer: "Log it in the app or message the assistant; we can suggest tighter reminders." },
  { question: "How do I see compartment assignments?", answer: "Check Refill Reminders or the schedule; each compartment shows its medication name." },
  { question: "How do I change compartment medication?", answer: "Edit the schedule for that compartment and update the medication details." },
  { question: "Can I set dose confirmations?", answer: "If enabled, tap confirm on reminders. This improves adherence accuracy." },
  { question: "How do I handle duplicate reminders?", answer: "Update the schedule to remove duplicates and keep only the intended times." },
  { question: "Can caregivers mark doses taken?", answer: "If caregiver permissions allow, they can log doses. Otherwise only the patient can." },
  { question: "How do I add a custom reminder sound?", answer: "Use system notification sounds; custom sounds depend on device OS support." },
  { question: "How do I see upcoming doses?", answer: "Dashboard countdown and schedule list show upcoming doses for the day." },
  { question: "How do I log OTC meds?", answer: "Add them as medications with appropriate times; still follow pharmacist guidance." },
  { question: "How do I log supplements?", answer: "Add them with dose times and note any food requirements or interactions." },
  { question: "Can I export a medication list?", answer: "Use Export/Backup if available, or copy from the schedule to share with a clinician." },
  { question: "How do I change notification times?", answer: "Edit dose times in the schedule; reminders follow those times." },
  { question: "What if my phone is on silent?", answer: "Reminders will vibrate/notify per system rules. Consider enabling critical alerts if supported." },
  { question: "Can I use widgets?", answer: "If widgets are supported, add the medication widget from your device’s widget gallery." },
  { question: "How do I see refill status?", answer: "Use the Refill Reminders section on the dashboard; it shows days left for each compartment." },
  { question: "Can I reorder compartments?", answer: "If sorting is supported, reorder in the schedule; otherwise compartments remain fixed labels." },
  { question: "How do I calibrate time?", answer: "Ensure device time is set to automatic network time to avoid drift." },
  { question: "How do I handle overlapping meds?", answer: "Stagger them if required for safety. Ask a clinician if two meds should be spaced apart." },
  { question: "Can I log blood pressure or glucose?", answer: "Use the vitals section if available, or record in notes/messages for your caregiver." },
  { question: "How do I get refill alerts sooner?", answer: "Adjust reminder lead time in Refill Reminders to alert at 5-7 days remaining." },
  { question: "Can I dismiss reminders?", answer: "Yes, but still log whether you took the dose to keep adherence accurate." },
  { question: "How do I reset my password?", answer: "Change it in Profile → Account. If you’re locked out, use the reset flow (if enabled) or contact support." },
  { question: "Why do I see Soumay as default?", answer: "Soumay is the demo user. Update your name/email in Profile → Account to personalize." },
  { question: "How do I update the app icon?", answer: "Icons come from the installed build; update via a new build if you need a different icon." },
  { question: "Can I use multiple caregivers?", answer: "If multi-caregiver support exists, you can invite more than one; otherwise only one caregiver is linked." },
  { question: "How do I review permissions?", answer: "Check device settings → App permissions for notifications, biometrics, storage if applicable." },
  { question: "How do I see error logs?", answer: "Use the in-app error boundary UI or developer tools in Expo/React Native when testing." },
  { question: "How do I contact support?", answer: "Use Help Center in Profile or send a message through the assistant with your issue." },
  { question: "How do I rename a medication?", answer: "Edit the medication entry in the schedule for the associated compartment." },
  { question: "Can I change dosage strength?", answer: "Only if prescribed. Update the schedule to reflect the new strength after clinician approval." },
  { question: "What if I lose internet?", answer: "You can still view schedule and log doses. Sync and messaging will resume when back online." },
  { question: "Can I disable vibrations?", answer: "Change notification preferences in system settings; vibration follows device rules." },
  { question: "How do I check last taken time?", answer: "View dose history or recent adherence log if available; otherwise note it in chat." },
  { question: "Can I set medication instructions?", answer: "Add notes like 'with food' or 'no alcohol' in the medication details if supported." },
  { question: "What if refill reminder is wrong?", answer: "Update pills remaining or daily doses for that compartment; reminders recalc based on those values." },
  { question: "Can I archive a medication?", answer: "Mark it inactive or remove it from the schedule; refill reminders will stop." },
  { question: "How do I handle tapering schedules?", answer: "Adjust dose amounts and times per day as instructed. Consider separate entries per phase." },
  { question: "Can I sync with calendar?", answer: "If calendar sync is supported, enable it in settings. Otherwise rely on app notifications." },
  { question: "How do I change units?", answer: "Units follow medication entries. Enter the correct mg/mL as prescribed." },
  { question: "What if I get duplicate alerts after time-zone changes?", answer: "Restart the app and verify dose times; ensure device time zone is correct." },
  { question: "How do I mark a dose as skipped?", answer: "Use the skip action on the reminder or log it in history if available." },
  { question: "Can I set quiet hours?", answer: "Use device Do Not Disturb for quiet hours; review morning reminders after quiet hours end." },
  { question: "How do I see which compartment to open?", answer: "Check the scheduled dose details; it lists the compartment letter and medication name." },
  { question: "Can I get instructions per medication?", answer: "Yes—open the medication detail in the schedule to view instructions you saved." },
  { question: "How do I prevent accidental double doses?", answer: "Log each dose when taken, keep reminders on, and avoid opening the same compartment twice per scheduled time." },
  { question: "How do I log PRN usage counts?", answer: "Add a PRN entry and tap log when taken. Respect max doses per day." },
  { question: "Can I get refill reminders via SMS/email?", answer: "If channel options exist, enable them in notification preferences; otherwise the app will notify locally." },
  { question: "How do I disable biometrics temporarily?", answer: "Toggle Biometric Login off in Profile → Preferences; you can re-enable later." },
  { question: "How do I test reminders?", answer: "Set a test dose time a few minutes ahead, wait for the notification, then revert to your normal schedule." },
  { question: "What if my device blocks background activity?", answer: "Allow background activity and disable battery optimization for the app to keep reminders timely." },
  { question: "Can I import medications from my clinician?", answer: "If EHR sync is available, connect via settings; otherwise enter them manually." },
  { question: "Can I see refill history?", answer: "Check Refill Reminders history if supported; otherwise track refills via notes or chat." },
  { question: "How do I schedule multiple doses in one day?", answer: "Add multiple times to the same medication entry; the app will alert at each time." },
  { question: "Can I set different reminder tones per medication?", answer: "Not typically; tones are global per device notification settings." },
  { question: "How do I escalate an urgent issue?", answer: "Use the SOS button if available or contact emergency services for severe symptoms." },
  { question: "Can I add insurance info?", answer: "Not required for reminders; if there’s a profile field, store it there for reference." }
];
